Dev issues#50 96
cesbo/help pull request #97
Opened 2023-06-23 11:14 UTC by ccErrors

Добавил статьи "[Hardware and drivers](https://cesbo.com/en/latest/linux/unsupported-sfp#)"

2023-06-27 09:06 UTC, and-cesbo requested changes

2023-06-27 09:06 UTC, and-cesbo commented on content/3.misc/1.tools-and-utilities/4.hardware-and-drivers/pt100-dvb-t-modulator.md
- Давай также как и DVB-C модулятор эту статью в Delivery -> Broadcasting
- после `---` надо пустую строку
- "Setup" и "Astra settings" - разделами

2023-06-27 09:06 UTC, and-cesbo commented on content/3.misc/1.tools-and-utilities/4.hardware-and-drivers/tbs-dvb-c-modulator.md
- Давай также как и DVB-C модулятор эту статью в Delivery -> Broadcasting
- после `---` надо пустую строку
- "Setup" и "Astra settings" - разделами

2023-06-27 09:06 UTC, and-cesbo commented on content/3.misc/2.articles/2.protocols/mpeg-ts.md
- `####` - нельзя использовать
- `###` - опять перепрыгнулось через уровень
- https://github.com/cesbo/help/blob/mkdocs/en/codex/transport/mpegts.md вот от сюда ещё можно перетащить. Как настраивать CBR в астре тут не надо, это просто общая статья про mpeg-ts

2023-06-27 09:06 UTC, and-cesbo commented on content/3.misc/2.articles/2.protocols/xmltv-format.md
- `####` - нельзя использовать
- `###` - опять перепрыгнулось через уровень
- после `---` - нужна пустая строка
- большие буквы в заголовках не нужны
- там где списки для описания используется куча пустых строк между описаниями. надо просто списком оформить (без пустых строк, просто `-` в начале каждой строки)

2023-06-27 16:46 UTC, ccErrors commented
@and-cesbo сделал вроде

2023-07-08 14:59 UTC, and-cesbo approved these changes

2023-07-08 15:00 UTC, merged